with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
mockname: "Mock{{.InterfaceName}}"
filename: "{{.InterfaceNameSnake}}_mock.go"
packages:
  github.com/m1ll3r1337/catalog-service/internal/app/repository:
    interfaces:
      Product:
      Category:
