// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/m1ll3r1337/catalog-service/internal/app/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/gofrs/uuid"
)

// MockCategory is an autogenerated mock type for the Category type
type MockCategory struct {
	mock.Mock
}

type MockCategory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategory) EXPECT() *MockCategory_Expecter {
	return &MockCategory_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, category
func (_m *MockCategory) Create(ctx context.Context, category entity.Category) error {
	ret := _m.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Category) error); ok {
		r0 = rf(ctx, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategory_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCategory_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - category entity.Category
func (_e *MockCategory_Expecter) Create(ctx interface{}, category interface{}) *MockCategory_Create_Call {
	return &MockCategory_Create_Call{Call: _e.mock.On("Create", ctx, category)}
}

func (_c *MockCategory_Create_Call) Run(run func(ctx context.Context, category entity.Category)) *MockCategory_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Category))
	})
	return _c
}

func (_c *MockCategory_Create_Call) Return(_a0 error) *MockCategory_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategory_Create_Call) RunAndReturn(run func(context.Context, entity.Category) error) *MockCategory_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, guid
func (_m *MockCategory) Delete(ctx context.Context, guid uuid.UUID) error {
	ret := _m.Called(ctx, guid)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, guid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategory_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCategory_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - guid uuid.UUID
func (_e *MockCategory_Expecter) Delete(ctx interface{}, guid interface{}) *MockCategory_Delete_Call {
	return &MockCategory_Delete_Call{Call: _e.mock.On("Delete", ctx, guid)}
}

func (_c *MockCategory_Delete_Call) Run(run func(ctx context.Context, guid uuid.UUID)) *MockCategory_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCategory_Delete_Call) Return(_a0 error) *MockCategory_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategory_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockCategory_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByGUIDs provides a mock function with given fields: ctx, guids
func (_m *MockCategory) GetByGUIDs(ctx context.Context, guids []uuid.UUID) ([]entity.Category, error) {
	ret := _m.Called(ctx, guids)

	if len(ret) == 0 {
		panic("no return value specified for GetByGUIDs")
	}

	var r0 []entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]entity.Category, error)); ok {
		return rf(ctx, guids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []entity.Category); ok {
		r0 = rf(ctx, guids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, guids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategory_GetByGUIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByGUIDs'
type MockCategory_GetByGUIDs_Call struct {
	*mock.Call
}

// GetByGUIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - guids []uuid.UUID
func (_e *MockCategory_Expecter) GetByGUIDs(ctx interface{}, guids interface{}) *MockCategory_GetByGUIDs_Call {
	return &MockCategory_GetByGUIDs_Call{Call: _e.mock.On("GetByGUIDs", ctx, guids)}
}

func (_c *MockCategory_GetByGUIDs_Call) Run(run func(ctx context.Context, guids []uuid.UUID)) *MockCategory_GetByGUIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *MockCategory_GetByGUIDs_Call) Return(_a0 []entity.Category, _a1 error) *MockCategory_GetByGUIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategory_GetByGUIDs_Call) RunAndReturn(run func(context.Context, []uuid.UUID) ([]entity.Category, error)) *MockCategory_GetByGUIDs_Call {
	_c.Call.Return(run)
	return _c
}

// InsideTx provides a mock function with given fields: ctx, fn
func (_m *MockCategory) InsideTx(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for InsideTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategory_InsideTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsideTx'
type MockCategory_InsideTx_Call struct {
	*mock.Call
}

// InsideTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(context.Context) error
func (_e *MockCategory_Expecter) InsideTx(ctx interface{}, fn interface{}) *MockCategory_InsideTx_Call {
	return &MockCategory_InsideTx_Call{Call: _e.mock.On("InsideTx", ctx, fn)}
}

func (_c *MockCategory_InsideTx_Call) Run(run func(ctx context.Context, fn func(context.Context) error)) *MockCategory_InsideTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *MockCategory_InsideTx_Call) Return(_a0 error) *MockCategory_InsideTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategory_InsideTx_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *MockCategory_InsideTx_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, name
func (_m *MockCategory) List(ctx context.Context, name *string) ([]entity.Category, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *string) ([]entity.Category, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *string) []entity.Category); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategory_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCategory_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - name *string
func (_e *MockCategory_Expecter) List(ctx interface{}, name interface{}) *MockCategory_List_Call {
	return &MockCategory_List_Call{Call: _e.mock.On("List", ctx, name)}
}

func (_c *MockCategory_List_Call) Run(run func(ctx context.Context, name *string)) *MockCategory_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*string))
	})
	return _c
}

func (_c *MockCategory_List_Call) Return(_a0 []entity.Category, _a1 error) *MockCategory_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategory_List_Call) RunAndReturn(run func(context.Context, *string) ([]entity.Category, error)) *MockCategory_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, category
func (_m *MockCategory) Update(ctx context.Context, category entity.Category) error {
	ret := _m.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Category) error); ok {
		r0 = rf(ctx, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategory_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCategory_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - category entity.Category
func (_e *MockCategory_Expecter) Update(ctx interface{}, category interface{}) *MockCategory_Update_Call {
	return &MockCategory_Update_Call{Call: _e.mock.On("Update", ctx, category)}
}

func (_c *MockCategory_Update_Call) Run(run func(ctx context.Context, category entity.Category)) *MockCategory_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Category))
	})
	return _c
}

func (_c *MockCategory_Update_Call) Return(_a0 error) *MockCategory_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategory_Update_Call) RunAndReturn(run func(context.Context, entity.Category) error) *MockCategory_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCategory creates a new instance of MockCategory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategory {
	mock := &MockCategory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
