// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/m1ll3r1337/catalog-service/internal/app/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/gofrs/uuid"
)

// MockProduct is an autogenerated mock type for the Product type
type MockProduct struct {
	mock.Mock
}

type MockProduct_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProduct) EXPECT() *MockProduct_Expecter {
	return &MockProduct_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, product
func (_m *MockProduct) Create(ctx context.Context, product entity.Product) error {
	ret := _m.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Product) error); ok {
		r0 = rf(ctx, product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProduct_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProduct_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - product entity.Product
func (_e *MockProduct_Expecter) Create(ctx interface{}, product interface{}) *MockProduct_Create_Call {
	return &MockProduct_Create_Call{Call: _e.mock.On("Create", ctx, product)}
}

func (_c *MockProduct_Create_Call) Run(run func(ctx context.Context, product entity.Product)) *MockProduct_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Product))
	})
	return _c
}

func (_c *MockProduct_Create_Call) Return(_a0 error) *MockProduct_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProduct_Create_Call) RunAndReturn(run func(context.Context, entity.Product) error) *MockProduct_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, guid
func (_m *MockProduct) Delete(ctx context.Context, guid uuid.UUID) error {
	ret := _m.Called(ctx, guid)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, guid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProduct_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProduct_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - guid uuid.UUID
func (_e *MockProduct_Expecter) Delete(ctx interface{}, guid interface{}) *MockProduct_Delete_Call {
	return &MockProduct_Delete_Call{Call: _e.mock.On("Delete", ctx, guid)}
}

func (_c *MockProduct_Delete_Call) Run(run func(ctx context.Context, guid uuid.UUID)) *MockProduct_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProduct_Delete_Call) Return(_a0 error) *MockProduct_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProduct_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockProduct_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByGUIDs provides a mock function with given fields: ctx, guids
func (_m *MockProduct) GetByGUIDs(ctx context.Context, guids []uuid.UUID) ([]entity.Product, error) {
	ret := _m.Called(ctx, guids)

	if len(ret) == 0 {
		panic("no return value specified for GetByGUIDs")
	}

	var r0 []entity.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]entity.Product, error)); ok {
		return rf(ctx, guids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []entity.Product); ok {
		r0 = rf(ctx, guids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, guids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProduct_GetByGUIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByGUIDs'
type MockProduct_GetByGUIDs_Call struct {
	*mock.Call
}

// GetByGUIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - guids []uuid.UUID
func (_e *MockProduct_Expecter) GetByGUIDs(ctx interface{}, guids interface{}) *MockProduct_GetByGUIDs_Call {
	return &MockProduct_GetByGUIDs_Call{Call: _e.mock.On("GetByGUIDs", ctx, guids)}
}

func (_c *MockProduct_GetByGUIDs_Call) Run(run func(ctx context.Context, guids []uuid.UUID)) *MockProduct_GetByGUIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *MockProduct_GetByGUIDs_Call) Return(_a0 []entity.Product, _a1 error) *MockProduct_GetByGUIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProduct_GetByGUIDs_Call) RunAndReturn(run func(context.Context, []uuid.UUID) ([]entity.Product, error)) *MockProduct_GetByGUIDs_Call {
	_c.Call.Return(run)
	return _c
}

// InsideTx provides a mock function with given fields: ctx, fn
func (_m *MockProduct) InsideTx(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for InsideTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProduct_InsideTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsideTx'
type MockProduct_InsideTx_Call struct {
	*mock.Call
}

// InsideTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(context.Context) error
func (_e *MockProduct_Expecter) InsideTx(ctx interface{}, fn interface{}) *MockProduct_InsideTx_Call {
	return &MockProduct_InsideTx_Call{Call: _e.mock.On("InsideTx", ctx, fn)}
}

func (_c *MockProduct_InsideTx_Call) Run(run func(ctx context.Context, fn func(context.Context) error)) *MockProduct_InsideTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *MockProduct_InsideTx_Call) Return(_a0 error) *MockProduct_InsideTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProduct_InsideTx_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *MockProduct_InsideTx_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, name, categoryGUID, minPrice, maxPrice
func (_m *MockProduct) List(ctx context.Context, name *string, categoryGUID *uuid.UUID, minPrice *int64, maxPrice *int64) ([]entity.Product, error) {
	ret := _m.Called(ctx, name, categoryGUID, minPrice, maxPrice)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *string, *uuid.UUID, *int64, *int64) ([]entity.Product, error)); ok {
		return rf(ctx, name, categoryGUID, minPrice, maxPrice)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *string, *uuid.UUID, *int64, *int64) []entity.Product); ok {
		r0 = rf(ctx, name, categoryGUID, minPrice, maxPrice)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *string, *uuid.UUID, *int64, *int64) error); ok {
		r1 = rf(ctx, name, categoryGUID, minPrice, maxPrice)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProduct_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockProduct_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - name *string
//   - categoryGUID *uuid.UUID
//   - minPrice *int64
//   - maxPrice *int64
func (_e *MockProduct_Expecter) List(ctx interface{}, name interface{}, categoryGUID interface{}, minPrice interface{}, maxPrice interface{}) *MockProduct_List_Call {
	return &MockProduct_List_Call{Call: _e.mock.On("List", ctx, name, categoryGUID, minPrice, maxPrice)}
}

func (_c *MockProduct_List_Call) Run(run func(ctx context.Context, name *string, categoryGUID *uuid.UUID, minPrice *int64, maxPrice *int64)) *MockProduct_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*string), args[2].(*uuid.UUID), args[3].(*int64), args[4].(*int64))
	})
	return _c
}

func (_c *MockProduct_List_Call) Return(_a0 []entity.Product, _a1 error) *MockProduct_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProduct_List_Call) RunAndReturn(run func(context.Context, *string, *uuid.UUID, *int64, *int64) ([]entity.Product, error)) *MockProduct_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, product
func (_m *MockProduct) Update(ctx context.Context, product entity.Product) error {
	ret := _m.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Product) error); ok {
		r0 = rf(ctx, product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProduct_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProduct_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - product entity.Product
func (_e *MockProduct_Expecter) Update(ctx interface{}, product interface{}) *MockProduct_Update_Call {
	return &MockProduct_Update_Call{Call: _e.mock.On("Update", ctx, product)}
}

func (_c *MockProduct_Update_Call) Run(run func(ctx context.Context, product entity.Product)) *MockProduct_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Product))
	})
	return _c
}

func (_c *MockProduct_Update_Call) Return(_a0 error) *MockProduct_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProduct_Update_Call) RunAndReturn(run func(context.Context, entity.Product) error) *MockProduct_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProduct creates a new instance of MockProduct. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProduct(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProduct {
	mock := &MockProduct{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
